name: 'CLI for Microsoft 365 Run Script'
description: 'Runs an CLI for Microsoft 365 script'
inputs:
  CLI_MICROSOFT365_SCRIPT_PATH:  
    description: 'Relative path of the script in your repo.'
  CLI_MICROSOFT365_SCRIPT:
    description: 'CLI for Microsoft 365 Script'
  IS_POWERSHELL:
    description: 'Used only with CLI_MICROSOFT365_SCRIPT. If true the assumption is the script passed in CLI_MICROSOFT365_SCRIPT will be a PowerShell script, otherwise the assumption is bash script. Default is false'
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: 'terminal'  
  color: 'blue'